### PR TITLE
[#173] Boto3 client kwargs passthrough

### PR DESCRIPTION
**Pull request by nk9**
**I have not tested this!** I don't have an SRP setup.

Please test it @Amejonah1200 and let me know if this will do what you need.

### CODE REVIEW

**Comment by Amejonah1200** [comment]
It looks functional, but this solution doesn't  allow IDEs to check for parameters (also mo auto-complete) and it has a sideeffect of modifying input dictionary.

**Comment by nk9** [comment]
This is true. Here is [the list of parameters accepted by the function](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client). And these are the ones missing right now:

- `api_version`
- `aws_session_token`
- `use_ssl`
- `verify`
- `endpoint_url`

So this PR would allow all 5 of those to be set as needed, but at the expense of missing IDE sugar. I could do it with `**kwargs` in the signature, but that won't improve the experience for IDE users.

Thoughts @pvizeli?

**Comment by Amejonah1200** [comment]
You can also just make them return default values, this would also not require code changes (add also type hints).

**Comment by nk9** [comment]
I understand what you're suggesting, but I'm saying it's a larger change because then we have to declare all the variables twice, pass them into the `utilities` function, and then conditionally pack them into the dictionary to be unpacked again into the client function call. I'm looking for guidance from the maintainer as to what approach he'd prefer.

**Review by pvizeli — APPROVED** [review]
I'm fine with that approach, pycognito is an wrapper around boto3 cognito. We doing things like this on other place too. Agree, maybe not that optimal, but if someone will add typehints, that work with TypedDicts. Fine for me to ditch support for python < 3.8

**Comment by nk9** [comment]
Great, thanks. BTW, I've run the code now and verified that it's succesfully passing values through.

**Comment by Amejonah1200** [comment]
Thanks everyone!

**Pull request merged**
